version: "3"
services:
  client:
    build: client
    image: t-rex-multiplayer-client
    restart: "${RESTART}"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  server:
    build: server
    image: t-rex-multiplayer-server
    restart: "${RESTART}"
    depends_on:
      - db
  db:
    image: "mariadb:10.7.3"
    ports:
      - "3306:3306"
    restart: "${RESTART}"
    volumes:
      - ./DB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_czech_ci']
